PokemonAPI/force-app/main/default/objects/Integration__mdt/Integration__mdt.object-meta.xml
<CustomObject>
    <description>Object to use in Pokemon integration.</description>
    <label>Integration</label>
    <pluralLabel>Integrations</pluralLabel>
</CustomObject>

PokemonAPI/force-app/main/default/objects/Integration__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>Field to store the endpoint.</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PokemonAPI/force-app/main/default/objects/Integration__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

PokemonAPI/force-app/main/default/classes/PokemonCallout.cls
public with sharing class PokemonCallout {
    
    public static void pokemonCallout(Contact contact) {
        Integration__mdt pokemonAPISettings = [SELECT EndPoint__c, Method__c FROM Integration__mdt];
        String endPointPokemon = pokemonAPISettings.EndPoint__c + Contact.FavoritePokemon__c;

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endPointPokemon);
        request.setMethod(pokemonAPISettings.Method__c);

        HttpResponse response = http.send(request);
        String jsonBody = response.getBody();

        if (response.getStatusCode() == 200) {
            System.debug('jsonBody' + jsonBody);
        }
    }
}